### ISSUE TITLE
Amazon announces deprecation of older API versions

### ISSUE THREAD

**Issue by chriscompton70** [garu/Amazon-CloudFront-Thin#4]
With Amazon's recent announcement that it will be deprecating the older versions of the Cloudfront API.
https://forums.aws.amazon.com/ann.jspa?annID=6697
I'm wondering if you'll be updating this module?

**Comment by chriscompton70** [comment]
Only 2 updates seem to be needed.

`diff Thin.pm Thin.pm_orig
71c71
<         'https://cloudfront.amazonaws.com/2018-11-05/distribution/'
---
>         'https://cloudfront.amazonaws.com/2015-04-17/distribution/'
197c197
<     return qq{<?xml version="1.0" encoding="UTF-8"?><InvalidationBatch xmlns="http://cloudfront.amazonaws.com/doc/2018-11-05/"><Paths><Quantity>$total_paths</Quantity><Items>$path_content</Items></Paths><CallerReference>$identifier</CallerReference></InvalidationBatch>};
---
>     return qq{<?xml version="1.0" encoding="UTF-8"?><InvalidationBatch xmlns="http://cloudfront.amazonaws.com/doc/2015-04-17/"><Paths><Quantity>$total_paths</Quantity><Items>$path_content</Items></Paths><CallerReference>$identifier</CallerReference></InvalidationBatch>};`

**Comment by chriscompton70** [comment]
Only 2 lines need an update

Line 71

Update:         `'https://cloudfront.amazonaws.com/2018-11-05/distribution/'`

 Original:        `'https://cloudfront.amazonaws.com/2015-04-17/distribution/'`

Line 197

Update:     `return qq{<?xml version="1.0" encoding="UTF-8"?><InvalidationBatch xmlns="http://cloudfront.amazonaws.com/doc/2018-11-05/"><Paths><Quantity>$total_paths</Quantity><Items>$path_content</Items></Paths><CallerReference>$identifier</CallerReference></InvalidationBatch>};`

Original;     `return qq{<?xml version="1.0" encoding="UTF-8"?><InvalidationBatch xmlns="http://cloudfront.amazonaws.com/doc/2015-04-17/"><Paths><Quantity>$total_paths</Quantity><Items>$path_content</Items></Paths><CallerReference>$identifier</CallerReference></InvalidationBatch>};`

**Comment by garu** [comment]
@chriscompton70 Thank you for using this module, and for taking the time not just to report the issue but also to work on a patch, which I have applied.

Version 0.05 is already on its way to CPAN, with your update credited on the Changes file, and an extra stability fix for weird filenames.

Thanks again!
